"""sync all models

Revision ID: 1ccd002a7a90
Revises: eaa370972844
Create Date: 2026-05-17 14:58:47.593702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccd002a7a90'
down_revision: Union[str, Sequence[str], None] = 'eaa370972844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table_name in inspector.get_table_names()


def _drop_leftover_batch_tables() -> None:
    for table_name in sa.inspect(op.get_bind()).get_table_names():
        if table_name.startswith('_alembic_tmp_'):
            op.drop_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_leftover_batch_tables()

    if not _has_table('subscriptions'):
        op.create_table('subscriptions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('plan', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('subscriptions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_subscriptions_plan'), ['plan'], unique=False)

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))
        batch_op.create_index(batch_op.f('ix_goals_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_title'), ['title'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('progress_percentage')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')
        batch_op.drop_column('target_date')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('goal_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_milestones_goal_id'))
        batch_op.create_index(batch_op.f('ix_milestones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_order_index'), ['order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_target_date'), ['target_date'], unique=False)
        batch_op.drop_column('title')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')
        batch_op.drop_column('completed')

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remainder', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('push_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_notification_settings_user_id'))
        batch_op.create_index(batch_op.f('ix_notification_settings_id'), ['id'], unique=False)
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('email_enabled')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_percent', sa.Float(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('logged_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_progress_logs_goal_id'))
        batch_op.create_index(batch_op.f('ix_progress_logs_completion_percent'), ['completion_percent'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.drop_column('completion_percentage')
        batch_op.drop_column('streak_days')
        batch_op.drop_column('goal_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('milestone_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.drop_column('title')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('priority')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('refresh_token_expires_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('refresh_token_revoked_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('refresh_token_revoked_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('refresh_token_expires_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('estimated_minutes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('milestone_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.NUMERIC(), nullable=False))
        batch_op.add_column(sa.Column('streak_days', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('completion_percentage', sa.FLOAT(), nullable=False))
        batch_op.create_foreign_key('fk_progress_logs_goal_id_goals', 'goals', ['goal_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_progress_logs_logged_at'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_id'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_completion_percent'))
        batch_op.create_index(batch_op.f('ix_progress_logs_goal_id'), ['goal_id'], unique=False)
        batch_op.alter_column('logged_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('completion_percent')

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('email_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('reminder_time', sa.TIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notification_settings_id'))
        batch_op.create_index(batch_op.f('ix_notification_settings_user_id'), ['user_id'], unique=1)
        batch_op.alter_column('push_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('remainder')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_milestones_target_date'))
        batch_op.drop_index(batch_op.f('ix_milestones_order_index'))
        batch_op.drop_index(batch_op.f('ix_milestones_id'))
        batch_op.create_index(batch_op.f('ix_milestones_goal_id'), ['goal_id'], unique=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('goal_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('progress_percentage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_goals_title'))
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_index(batch_op.f('ix_goals_id'))
        batch_op.drop_index(batch_op.f('ix_goals_deadline'))
        batch_op.drop_index(batch_op.f('ix_goals_category'))
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('deadline')

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
