"""Initial SQLite migration

Revision ID: 587ecad0657e
Revises: 
Create Date: 2026-05-19 16:32:24.534721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587ecad0657e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_plan'), ['plan'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_sessions_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_settings_id'), ['id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('goal_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_activity_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_activity_id'), ['id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_order_index'), ['order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_updated_at'), ['updated_at'], unique=False)

    op.create_table('progress_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_logs_completion_percentage'), ['completion_percentage'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_logged_at'), ['logged_at'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_completed_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_logs_logged_at'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_id'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_completion_percentage'))

    op.drop_table('progress_logs')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_updated_at'))
        batch_op.drop_index(batch_op.f('ix_milestones_title'))
        batch_op.drop_index(batch_op.f('ix_milestones_target_date'))
        batch_op.drop_index(batch_op.f('ix_milestones_order_index'))
        batch_op.drop_index(batch_op.f('ix_milestones_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_created_at'))

    op.drop_table('milestones')
    with op.batch_alter_table('goal_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_activity_id'))
        batch_op.drop_index(batch_op.f('ix_goal_activity_created_at'))
        batch_op.drop_index(batch_op.f('ix_goal_activity_activity_date'))

    op.drop_table('goal_activity')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_settings_id'))

    op.drop_table('notification_settings')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_updated_at'))
        batch_op.drop_index(batch_op.f('ix_goals_title'))
        batch_op.drop_index(batch_op.f('ix_goals_target_date'))
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_index(batch_op.f('ix_goals_id'))
        batch_op.drop_index(batch_op.f('ix_goals_deadline'))
        batch_op.drop_index(batch_op.f('ix_goals_created_at'))
        batch_op.drop_index(batch_op.f('ix_goals_category'))

    op.drop_table('goals')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_date'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_completed_at'))

    op.drop_table('focus_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
